#!/usr/bin/env php
<?php

if (!ini_get('date.timezone')) {
    ini_set('date.timezone', 'UTC');
}

foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        define('TESTBENCH_COMPOSER_INSTALL', $file);
        break;
    }
}

unset($file);

if (!defined('TESTBENCH_COMPOSER_INSTALL')) {
    fwrite(STDERR,
        'You need to set up the project dependencies using the following commands:' . PHP_EOL .
        'wget http://getcomposer.org/composer.phar' . PHP_EOL .
        'php composer.phar install' . PHP_EOL
    );
    die(1);
}

require TESTBENCH_COMPOSER_INSTALL;

$app = new \Cilex\Application('testbench', '1.0.0');
$app->command(new \attachmentgenie\testbench\command\DbTestCommand());
$app->command(new \attachmentgenie\testbench\command\InitCommand());
$app->command(new \attachmentgenie\testbench\command\PhpMongoCommand());
$app->command(new \attachmentgenie\testbench\command\PhpMySQLCommand());
$app->run();